# Generated by Django 3.1.2 on 2020-11-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mobile_number',
        ),
    ]
