# Generated by Django 3.1.3 on 2020-11-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='refferal_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='reffered_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
