# Generated by Django 3.1.2 on 2020-11-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0002_auto_20201107_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
