# Generated by Django 3.1.3 on 2020-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0002_auto_20201124_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='refferal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reffered_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='refferal_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reffered_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
