# Generated by Django 3.1.3 on 2020-11-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0002_auto_20201120_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dealer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_cart_app.dealer'),
        ),
    ]
