# Generated by Django 3.1.2 on 2020-11-09 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0003_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dealer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_cart_app.dealer'),
        ),
    ]
