# Generated by Django 3.1.3 on 2020-11-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0003_order_dealer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=220, null=True)),
                ('discount_amount', models.FloatField(null=True)),
                ('offer_start', models.DateField(auto_now_add=True, null=True)),
                ('offer_expiry', models.DateField(null=True)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_cart_app.dealer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_cart_app.product')),
            ],
        ),
    ]
