# Generated by Django 3.1.2 on 2020-11-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart_app', '0005_remove_order_dealer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
    ]
